Traceback (most recent call last):
  File "/home/daniil/Python/pp_labs/src/mod5/app/task4.py", line 31, in <module>
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
